### ISSUE TITLE
Support input arguments templating

### ISSUE THREAD

**Issue by guoger** [Hyperledger-TWGC/tape#109]
today, `tape` only support static and fixed arguments upon start. Although this is way too limited. We need to pick and support a templating language. For example: https://ghz.sh/docs/examples#metadata-using-template-variables

**Comment by guoger** [comment]
cc @SamYuan1990

**Comment by wangxinalex** [comment]
How about the `dynamic variables` in postman? https://learning.postman.com/docs/writing-scripts/script-references/variables-list/

**Comment by SamYuan1990** [comment]
> How about the `dynamic variables` in postman? https://learning.postman.com/docs/writing-scripts/script-references/variables-list/. Some random data generator can be leveraged like https://github.com/brianvoe/gofakeit

well, my personal opinion doesn't limit for any kind of implementation.
for post man, well @wangxinalex could you explain more about how integrate post man with tape(a golang base program?)
for the random data generator is a good point. however, if we extend our view. the use case is that

tape user input something in config.yaml `xxx word` and during tape running replace `xxx word` with data.
for random case, if user wants random data, this library is very good for us.
@guoger , could you please help comparing the different between https://ghz.sh/docs/examples#metadata-using-template-variables and https://ghz.sh/docs/examples#metadata-using-template-variables ?

**Comment by wangxinalex** [comment]
> > How about the `dynamic variables` in postman? https://learning.postman.com/docs/writing-scripts/script-references/variables-list/. Some random data generator can be leveraged like https://github.com/brianvoe/gofakeit
> 
> well, my personal opinion doesn't limit for any kind of implementation.
> for post man, well @wangxinalex could you explain more about how integrate post man with tape(a golang base program?)
> for the random data generator is a good point. however, if we extend our view. the use case is that
> 
> tape user input something in config.yaml `xxx word` and during tape running replace `xxx word` with data.
> for random case, if user wants random data, this library is very good for us.
> @guoger , could you please help comparing the different between https://ghz.sh/docs/examples#metadata-using-template-variables and https://ghz.sh/docs/examples#metadata-using-template-variables ?

In my view, the `dynamic variables` in postman could provide some insights for tape due since they are both popular request generator. It is unnecessary to port these features from postman 100% because it is based on Javascript, instead we can try to leverage fake data generators like https://github.com/brianvoe/gofakeit to produce some fake data with semantic meaning.

On the other hand, `ghz` can replace templates with some contextual data https://github.com/bojand/ghz/blob/06f029c14c97612a09095f55075474442ffc8243/runner/calldata.go#L24, of course which can be seen as some random info source, however this may be insufficient if we want semantically meaningful payload.

**Comment by guoger** [comment]
> How about the `dynamic variables` in postman? [learning.postman.com/docs/writing-scripts/script-references/variables-list](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/). Some random data generator can be leveraged like [brianvoe/gofakeit](https://github.com/brianvoe/gofakeit)

this looks promising.

Suppose following scenario:
```
1. create 1M accounts with random initial balance, then
2. randomly transfer among those accounts
```
1 should be easy with `dynamic variable`. Although I'm scratching my head around 2, where accounts are inherited from 1.

Anyway, satisfying 1 should be a good starting point already, and we could always build on top of it.

@wangxinalex interested?

**Comment by wangxinalex** [comment]
> > How about the `dynamic variables` in postman? [learning.postman.com/docs/writing-scripts/script-references/variables-list](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/). Some random data generator can be leveraged like [brianvoe/gofakeit](https://github.com/brianvoe/gofakeit)
> 
> this looks promising.
> 
> Suppose following scenario:
> 
> ```
> 1. create 1M accounts with random initial balance, then
> 2. randomly transfer among those accounts
> ```
> 
> 1 should be easy with `dynamic variable`. Although I'm scratching my head around 2, where accounts are inherited from 1.
> 
> Anyway, satisfying 1 should be a good starting point already, and we could always build on top of it.
> 
> @wangxinalex interested?

Sure, let's start with simple semantic random variables.
