### ISSUE TITLE
tips part update in read me, as document enhancement

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/tape#116]
I am fine with current context.
I am not sure, if we'd better refactor this part with link to https://prometheus.io/docs/introduction/overview/ (if we suggestion user use prometheus...)

so that tips can be refactor as:
tips:
1. network samples....
1. monitor tool suggestion....

and I suppose later we are able to use some result from probe to replace `Increase number of messages per block in your channel configuration may help`, as `adjust parameter for xxx may help for sample and ... `

but I suppose the content update can be in further version/pr.

_Originally posted by @SamYuan1990 in https://github.com/guoger/tape/pull/114#discussion_r535951048_

**Comment by SamYuan1990** [comment]
it's better to work together with #131

**Comment by davidkhala** [comment]
Link discussion https://wiki.hyperledger.org/pages/viewpage.action?pageId=41591622&focusedCommentId=41591963#comment-41591963
for network samples provider

**Comment by SamYuan1990** [comment]
would you like to take this ticket? @davidkhala

**Comment by davidkhala** [comment]
@SamYuan1990 to be clarify, is it what you means?
----------------------
tips:

- network samples: show what current network boostrap tool are used in CI

- monitor tool suggestion: a link to prometheus

**Comment by SamYuan1990** [comment]
> @SamYuan1990 to be clarify, is it what you means?
> 
> ## tips:
> * network samples: show what current network boostrap tool are used in CI
> * monitor tool suggestion: a link to prometheus

当前的tips混杂了很多内容。
比如
```
Put this generator closer to Fabric, or even on the same machine. This is to prevent network bandwidth from being the bottleneck.

Increase number of messages per block in your channel configuration may help
```
第一项在我看来是一个通用的性能测试提速的方式（网络问题） 是否考虑放入 https://github.com/Hyperledger-TWGC/fabric-performance-wiki/issues/9
第二项在我看来是fabric配置问题。或者说如何配置fabric从而获得更高的tps。

这两部分内容在我看来应该不是Tape的使用tips。
因此
```
tips:
network samples: show what current network boostrap tool are used in CI

monitor tool suggestion: a link to prometheus
```
不如考虑添加一下如何使用监控或者如何通过test-net快速启动。

**Comment by davidkhala** [comment]
@SamYuan1990 我觉得倒是作为FAQ或者几个置顶issue来放置这些讨论应该就可以了，本身不作为tape的部分。
所以我直接删掉这个章节OK么？

**Comment by SamYuan1990** [comment]
> @SamYuan1990 我觉得倒是作为FAQ或者几个置顶issue来放置这些讨论应该就可以了，本身不作为tape的部分。
> 所以我直接删掉这个章节OK么？

我觉得ok

**Comment by davidkhala** [comment]
已经迁移到 wiki部分 https://github.com/Hyperledger-TWGC/tape/wiki

**Comment by SamYuan1990** [comment]
> @SamYuan1990 已经迁移到 wiki部分 https://github.com/Hyperledger-TWGC/tape/wiki, 不过我们现在已经有了FAQ.md作为文档。是否作为代码形式的FAQ比wiki更好一点？

https://github.com/Hyperledger-TWGC/tape/blob/master/docs/FAQ.md？

**Comment by davidkhala** [comment]
> > @SamYuan1990 已经迁移到 wiki部分 https://github.com/Hyperledger-TWGC/tape/wiki, 不过我们现在已经有了FAQ.md作为文档。是否作为代码形式的FAQ比wiki更好一点？
> 
> [https://github.com/Hyperledger-TWGC/tape/blob/master/docs/FAQ.md？](https://github.com/Hyperledger-TWGC/tape/blob/master/docs/FAQ.md%EF%BC%9F)

是的，维护者怎么决策？
@guoger @stone-ch

**Comment by guoger** [comment]
我觉得做一个FAQ挺好
