### ISSUE TITLE
Migrate and fix Azure pipeline to TWGC/Tape

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/tape#139]
**Describe the bug**
Due to migration, some Azure managed secret not available in TWGC vault now. 
The Azure pipeline file is considered not properly configured. 

**To Reproduce**
When Azure pipeline in TWGC triggred

**Logs**
There was a resource authorization issue: "The pipeline is not valid. Job BuildAndReleaseBinaries: Step GitHubRelease input gitHubConnection references service connection github.com_stone-ch which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

**Additional context**
https://dev.azure.com/Hyperledger/TWGC/_build/results?buildId=29187&view=results

**Comment by davidkhala** [comment]
Closed by #141

**Comment by SamYuan1990** [comment]
@stone-ch stone， please also add with 2.2 version test ref https://github.com/hyperledger/fabric/pull/2316#discussion_r566928965
