### ISSUE TITLE
Require for tape output explaination

### ISSUE THREAD

**Issue by TurbeTao** [Hyperledger-TWGC/tape#146]
### Is your proposal related to a problem?

After I successfully ran the Tape in my fabric sample, I got results with three columns: time, block, and tnx. 

However, I didn't totally understand what these indicators mean as I have not found related documents in  https://github.com/Hyperledger-TWGC/tape .

In addition,  where/how can I get results such as latency and TPS. 

### Describe the solution you'd like

Hope the Tape outputs could be more intuitive or more explanations in README. Thanks

**Comment by SamYuan1990** [comment]
Thanks @TurbeTao ,

Let me explain your question one by one.
```
Time     1.78s	Block     41	Tx     10
Time     1.79s	Block     42	Tx     10
```
1. Time means the duration from 1st tx send to now.
1. The block number, to be honest, from grpc response. https://github.com/Hyperledger-TWGC/tape/blob/master/pkg/infra/observer.go#L79 It is peer block height maybe, as far as I remember. 
 - For ex, `./tape -n 500` will starts from 0 ~ 500 blocks and if we run another 0 ~ 500, the Block number seems starts from 501 to 10001 maybe?
1. Tx is the tx number inside the Block.

for latency, it is still in development, see https://github.com/Hyperledger-TWGC/tape/issues/94

for TPS... I suppose you will get tps after all tx completed.
Please ref my sample as Tape CI here.
https://dev.azure.com/Hyperledger/TWGC/_build/results?buildId=29368&view=logs&j=8d03cc15-4df7-568b-60a2-97dabd397d21&t=63bb61fd-6838-5eea-5642-3155fa8636f7&l=1000

the TPS is calculated by total tx/total time.
```
tx: 500, duration: 1.879948581s, tps: 265.964721
500/1.87xxx s = 265.964721 tx/s
```

thanks and regards

**Comment by TurbeTao** [comment]
So many thanks for your prompt reply and explanation. 

So can I understand that only two performance indicators I can get from current Tape? 

**1. Success rate**.  for example, if I  set the ./tape -n 500, and 500 blocks are generated finally (shown in terminal), I can tell the RATE is 100%.
**2. TPS**. As you have explained.  tnx/duration

** Besides, I just wonder are there any other indicators I can derive from tape results**

BTW, good to know know the latency evaluation is under development. Appreciate your efforts.

**Comment by SamYuan1990** [comment]
> So many thanks for your prompt reply and explanation.
> 
> So can I understand that only two performance indicators I can get from current Tape?
> 
> **1. Success rate**. for example, if I set the ./tape -n 500, and 500 blocks are generated finally (shown in terminal), I can tell the RATE is 100%.
> **2. TPS**. As you have explained. tnx/duration
> 
> ** Besides, I just wonder are there any other indicators I can derive from tape results**
> 
> BTW, good to know know the latency evaluation is under development. Appreciate your efforts.

For success rate, please ref https://github.com/Hyperledger-TWGC/tape/issues/14

For other indicators, well as Tape road map, we will following https://github.com/Hyperledger-TWGC/fabric-performance-wiki/blob/master/performance-whitepaper.md as guide/reference.

**Comment by lyp830414** [comment]
I'd like to take a task which add more explaination according to how it works & how does probe use it for performance test, etc. (I may start the work after all the Probe test-cases' working done :-) .

**Comment by SamYuan1990** [comment]
> I'd like to take a task which add more explaination according to how it works & how does probe use it for performance test, etc. (I may start the work after all the Probe test-cases' working done :-) ). @SamYuan1990

thanks
