### ISSUE TITLE
The threshold in BlockCollector does not take effect

### ISSUE THREAD

**Issue by hellosmallstone** [Hyperledger-TWGC/tape#149]
**Describe the bug**
In the scenario of monitoring multiple peers, if the number of threshold peers receive all transactions, txs can be considered as writed successful. However, the current implementation has a bug. As long as a peer receives all transactions, the monitoring process is deemed to be over and the program exits, which is a big deviation from the original design.
In addition, closing channel finishCh(https://github.com/Hyperledger-TWGC/tape/blob/master/pkg/infra/observer.go#L64) may panic, which has been closed in other goroutines.

**To Reproduce**

**Expected behavior**
The threshold in BlockCollector takes affect.

**Logs**
Attach logs from Tape/Peer/Orderer here. **And please format them with markdown!**

**Additional context**

**Comment by SamYuan1990** [comment]
@hellosmallstone , would you like to fix it with a pr?
