### ISSUE TITLE
Can user define transaction amount when testing tape

### ISSUE THREAD

**Issue by TurbeTao** [Hyperledger-TWGC/tape#156]
### Is your proposal related to a problem?

1) When I use tape to test my fabric network, the tape sets 10 transactions in each block by default. I just wondering where I can change this setting? It seems I cannot change it in the configure.yaml.

2) After testing, I quired blockchain height, and I found all the transactions that used for the test were really stored in ledger and can not be removed. So does Tape has a "clear" mechanism like caliper? Thanks

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

so many thanks to this awesome tape project, which frees me from the caliper.

(Write your answer here.)

**Comment by SamYuan1990** [comment]
Sorry for reply late. as I suffered from conjunctivitis recently.
For your 1st question, you'd better learn block setting from fabric doc. `MaxMessageCount`
For your 2nd question, is out of tape's design.  So far, Tape is just a very simple traffic generator. Which means setup and clear up are out of scope. You can ref Probe as a sample which may help your understand more. https://github.com/SamYuan1990/Probe

**Comment by guoger** [comment]
@TurbeTao out of curiosity, how does `Caliper` _remove_ the ledger?
