### ISSUE TITLE
`BlockCollector` should be able to detect repeated block (from same observer) and exclude it from block counting.

### ISSUE THREAD

**Issue by guoger** [Hyperledger-TWGC/tape#165]
there might be chance (probably not now) that a block from same orderer **shows up twice**, and block collector could not distinguish it, and still uses it for counting.

**Comment by yiwenlong** [comment]
🙋

**Comment by hellosmallstone** [comment]
#172 has been merged, this issue can be closed!
@guoger @SamYuan1990
