### ISSUE TITLE
wrong binary files for release v0.1.2

### ISSUE THREAD

**Issue by dexhunter** [Hyperledger-TWGC/tape#178]
**Describe the bug**

Hi, release v1.0.2 only includes the config file (about 619B) without the binary. Please help to fix it. Thanks!
![image](https://user-images.githubusercontent.com/6930518/124237066-ba528d80-db49-11eb-83e0-3bc3fd651380.png)
![image](https://user-images.githubusercontent.com/6930518/124237122-c5a5b900-db49-11eb-84c9-a4cf8d871556.png)
![image](https://user-images.githubusercontent.com/6930518/124237203-d9511f80-db49-11eb-9d2e-e617c9505d87.png)

**Comment by dexhunter** [comment]
cc @guoger @SamYuan1990

**Comment by davidkhala** [comment]
我们直接删除这个release可以么？

**Comment by SamYuan1990** [comment]
可以。弄个新的？

**Comment by davidkhala** [comment]
DONE, 我保留着这个release，不过将有问题的archive删除了，保留了源码
