### ISSUE TITLE
Unable to use function other than `GetAllAssets`

### ISSUE THREAD

**Issue by dexhunter** [Hyperledger-TWGC/tape#181]
**Describe the bug**

I am trying to use different chaincode functions such as `ReadAsset` which requires an `ID` for input. I modified the `config.yaml` to 
```
args:
     - ReadAsset
     -  1
```
or something similar but got the following error:

![image](https://user-images.githubusercontent.com/6930518/124788142-b1afec00-df7b-11eb-83e9-be71a6447ed3.png)

**Expected behavior**

Use a different chaincode function such as `UpdateAsset` (to test orderer capacity) or `ReadAsset` (is this one the read-only operation?)

**Comment by dexhunter** [comment]
related #109

**Comment by SamYuan1990** [comment]
in fact, we may need a step to invoke some chaincode as init function before we start...
but for tape, we don't deploy any chaincode as a big diff from caliper. So, I am not sure if we need to support this feature or not.
@guoger

**Comment by SamYuan1990** [comment]
in fact, we may need a step to invoke some chaincode as init function before we start...
but for tape, we don't deploy any chaincode as a big diff from caliper. So, I am not sure if we need to support this feature or not.
@guoger

**Comment by SamYuan1990** [comment]
@dexhunter , please find sample in the pr. and I am going to close this issue for now as the usage covered in #184 by CI. if you have further question please free to reopen this one.
