### ISSUE TITLE
An error was encountered during startup

### ISSUE THREAD

**Issue by 397341805** [Hyperledger-TWGC/tape#199]
The following bug occurred when I used tape to test the network
ERRO[0000] failed to create block collector: threshold and total must be greater than zero

**Comment by SamYuan1990** [comment]
https://github.com/Hyperledger-TWGC/tape/blob/e87f926a400d776104b09b3790bc0e4d4c836b06/pkg/infra/block_collector.go#L34

https://github.com/Hyperledger-TWGC/tape/blob/master/test/config14org1andorg2.yaml#L24

please check your config.

**Comment by luwei941** [comment]
我也遇到这个问题了还没有解决，我用fabric1.4.4中fabric-sample下的first-network测试的，这是我的配置文件[https://gitee.com/lw941cyy/tape/commit/d0d171dbf6dff0eab8a8fa6ecfa2806c7e5b3ee8](url)

**Comment by SamYuan1990** [comment]
> 我也遇到这个问题了还没有解决，我用fabric1.4.4中fabric-sample下的first-network测试的，这是我的配置文件[https://gitee.com/lw941cyy/tape/commit/d0d171dbf6dff0eab8a8fa6ecfa2806c7e5b3ee8](url)

请好好检查您所使用的配置文件，谢谢。
