### ISSUE TITLE
 fabric1.4.6版本first network使用tape测试时（./tape -c config.yaml -n 4000）错误failed to create block collector: threshold and total must be greater than zero 

### ISSUE THREAD

**Issue by luwei941** [Hyperledger-TWGC/tape#203]
**Describe the bug**

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Logs**
Attach logs from Tape/Peer/Orderer here. **And please format them with markdown!**

**Additional context**

**Comment by luwei941** [comment]
lw:/opt/gopath/src/github.com/hyperledger/fabric-samples/first-network/tape$ sudo ./tape -c config.yaml -n 1
ERRO[0000] failed to create block collector: threshold and total must be greater than zero

**Comment by SamYuan1990** [comment]
duplicate with https://github.com/Hyperledger-TWGC/tape/issues/199

**Comment by SamYuan1990** [comment]
please check your config file carefully.
