### ISSUE TITLE
Logging supports with jaeger

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/tape#223]
### Is your proposal related to a problem?
N/A

(Write your answer here.)

### Describe the solution you'd like
Ref to https://github.com/jaegertracing/jaeger/blob/master/examples/hotrod/pkg/log/factory.go#L44 make the logging supports for jaeger.

(Describe your proposed solution here.)

### Describe alternatives you've considered
Considering running tape in container/k8s, by adding this kind of supports, we are able to trace logging by jaeger(as open tracing) fmt/file output as fluentd/console. 

(Write your answer here.)

### Additional context
If possible, please also help refactor with log system.

(Write your answer here.)

**Comment by SamYuan1990** [comment]
if env jaeger endpoints then send log to jaeger.
should tracing for each tx with a span.
for each business process should covered by a span.
for each IO waiting for SUT response should covered by a span.

**Comment by SamYuan1990** [comment]
![image](https://user-images.githubusercontent.com/7820992/141688598-da22d8de-5b07-4a57-b1de-9a6418639b03.png)

**Comment by SamYuan1990** [comment]
![image](https://user-images.githubusercontent.com/7820992/141783841-a4cee4c5-3275-4b58-b2f6-0c34e37d6e6f.png)

**Comment by SamYuan1990** [comment]
![Uploading image.png…]()
add a pic if we apply open tracing at peer and orderer side.

**Comment by davidkhala** [comment]
@SamYuan1990 Sam,这个issue会同时替代现在的logger `github.com/sirupsen/logrus`么？

**Comment by SamYuan1990** [comment]
> @SamYuan1990 Sam,这个issue会同时替代现在的logger `github.com/sirupsen/logrus`么？

目前不会。
