### ISSUE TITLE
Transaction only succeed once in a single tape experiment 

### ISSUE THREAD

**Issue by hsj576** [Hyperledger-TWGC/tape#229]
**Describe the bug**
I use tape to test the tps of fabric. Tape sends 100 transactions of "Invoke A B 1" to fabric. However, only one transaction succeed.

**To Reproduce**
1. My environment: 
Linux version 4.4.0-186-generic (buildd@lcy01-amd64-002) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) )
fabric2.4
go version go1.16.7 linux/amd64
Docker version 20.10.7, build f0df350
docker-compose version 1.25.4, build 8d51620a
tape newest

2. test-network config
BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

3. tape config
channel: mychannel
chaincode: abstore
args:
  - Invoke
  - A
  - B
  - 1
4. ./network.sh up -s couchdb
5. ./network.sh createChannel -s couchdb
6. ./network.sh deployCC -ccn abstore -ccp ../chaincode/abstore/go/ -ccl go
7. peer chaincode invoke -o localhost:7050 --ordererTLSHostnameOverride orderer.example.com --tls --cafile "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem" -C mychannel -n abstore --peerAddresses localhost:7051 --tlsRootCertFiles "${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt" --peerAddresses localhost:9051 --tlsRootCertFiles "${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt" -c '{"Args":["Init","A","1000","B","1000"]}'
8. ./tape -c config.yaml -n 100
9. peer chaincode query -C mychannel -n abstore -c '{"Args":["Query","A"]}'

**Expected behavior**
A should be 9990 because there are 10 blocks and every block should has one success transaction. However A is 9999 which means that only one transaction succeed.

**Logs**
Attach logs from Tape/Peer/Orderer here. **And please format them with markdown!**

**Additional context**

**Comment by SamYuan1990** [comment]
In an assuming, the 100 tx based on 1st block. and then when fabric peer due with MVCC, as all 100 tx based on same block, then those 99 tx will fails with MVCC, but 1 tx success. so it should be not from 9999 to 9990

**Comment by hsj576** [comment]
> In an assuming, the 100 tx based on 1st block. and then when fabric peer due with MVCC, as all 100 tx based on same block, then those 99 tx will fails with MVCC, but 1 tx success. so it should be not from 9999 to 9990

Thanks for your reply. It's a good point. However, I have another question: When Tape measures TPS, it includes invalid transactions in the block. However, will the different number of valid transactions in the block affect the TPS measured by Tape? For example, if only one transaction in 100 transactions is valid and 10 transactions in 100 transactions are valid, is the TPS measured by Tape the same?

**Comment by SamYuan1990** [comment]
> > In an assuming, the 100 tx based on 1st block. and then when fabric peer due with MVCC, as all 100 tx based on same block, then those 99 tx will fails with MVCC, but 1 tx success. so it should be not from 9999 to 9990
> 
> Thanks for your reply. It's a good point. However, I have another question: When Tape measures TPS, it includes invalid transactions in the block. However, will the different number of valid transactions in the block affect the TPS measured by Tape? For example, if only one transaction in 100 transactions is valid and 10 transactions in 100 transactions are valid, is the TPS measured by Tape the same?

At personal point of view, in fabric transaction model, a failed tx with MVCC... go through most the steps.(or say majority 
 of the process as endorsement and consensus), meanwhile in real world, there’s  still something wrong at sometimes, that's why we have MVCC check. (double spending?)
If we say success or not as correction rate, that's fine.
So far, just to cover all txs. and there some plan to extend the mode, as for sample https://github.com/Hyperledger-TWGC/tape/issues/94, but for my personal point of view, should we monitoring by tape or dashboard?

for metrics and others, please take a look at https://github.com/Hyperledger-TWGC/fabric-performance-wiki/blob/master/performance-whitepaper.md
