### ISSUE TITLE
Tape ERRO[0000] ProposalResponsePayloads from Peers do not match

### ISSUE THREAD

**Issue by hsj576** [Hyperledger-TWGC/tape#230]
**Describe the bug**
I use tape to test the tps of fabric. Tape sends 200 transactions of "Invoke A B 1" to fabric. However, Tape is Broken with error:
ERRO[0000] ProposalResponsePayloads from Peers do not match 

**To Reproduce**
1. My environment: 
Linux version 4.4.0-186-generic (buildd@lcy01-amd64-002) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) )
fabric2.4
go version go1.16.7 linux/amd64
Docker version 20.10.7, build f0df350
docker-compose version 1.25.4, build 8d51620a
tape newest

2. test-network config
BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

3. tape config
channel: mychannel
chaincode: abstore
args:
  - Invoke
  - A
  - B
  - 1
4. ./network.sh up -s couchdb
5. ./network.sh createChannel -s couchdb
6. ./network.sh deployCC -ccn abstore -ccp ../chaincode/abstore/go/ -ccl go
7. peer chaincode invoke -o localhost:7050 --ordererTLSHostnameOverride orderer.example.com --tls --cafile "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem" -C mychannel -n abstore --peerAddresses localhost:7051 --tlsRootCertFiles "${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt" --peerAddresses localhost:9051 --tlsRootCertFiles "${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt" -c '{"Args":["Init","A","1000","B","1000"]}'
8. ./tape -c config.yaml -n 200

**Expected behavior**
It should work, but Tape is broken with error:
ERRO[0000] ProposalResponsePayloads from Peers do not match 
When the arg is [./tape -c config.yaml -n 100], it works.
When the arg is [./tape -c config.yaml -n 1000], Tape is broken with error:
ERRO[0000] Err processing proposal: rpc error: code = Canceled desc = context canceled, status: unknown, addr: localhost:9051
ERRO[0000] Err processing proposal: rpc error: code = Canceled desc = context canceled, status: unknown, addr: localhost:7051
ERRO[0000] recv broadcast err: rpc error: code = Canceled desc = context canceled, status: <nil> 
ERRO[0000] ProposalResponsePayloads from Peers do not match

**Comment by SamYuan1990** [comment]
see https://github.com/Hyperledger-TWGC/tape/issues/131
