### ISSUE TITLE
Is there have any way to report TPS for commitOnly/endorsementOnly  option?

### ISSUE THREAD

**Issue by gbl1124** [Hyperledger-TWGC/tape#238]
### Is your proposal related to a problem?

Hi Guys, I am try using commitOnly/endorsementOnly  option.
But there have no TPS report from the result, just report "empty endorsement policy".
Is there any more setup need for this options? Or there have no this feature for report TPS?

### Describe the solution you'd like
Could report the TPS from the result report.
Thank you very much~

**Comment by SamYuan1990** [comment]
ref to CI log:
https://dev.azure.com/Hyperledger/TWGC/_build/results?buildId=48128&view=logs&j=7cc4919e-7604-5b3d-4046-113f7a4a0843&t=41d9e55c-8c73-5183-9a6f-249cb9eb6101&l=3071

https://dev.azure.com/Hyperledger/TWGC/_build/results?buildId=48128&view=logs&j=42e0d588-4a05-5e49-cd2d-d02bafda4323&t=f5c4f82f-c626-5d7d-8eab-3a1459ea1449&l=8957

There is TPS in result report.

BTW, 
- I am really recommend you to take a look at https://github.com/Hyperledger-TWGC/fabric-performance-wiki/blob/master/performance-whitepaper.md

- To reproduce your issue, could you please share with your start script?

**Comment by SamYuan1990** [comment]
For commitOnly/endorsementOnly mode... some how it is wired to calculate with TPS.
as endorsementOnly is only for query, but not block generation.
and for commitOnly, it used for test with consensus but not for a full traffic test.

**Comment by gbl1124** [comment]
Thank you very much~
I found branches  alpha support  commitOnly/endorsementOnly, so I build a tape and runs at test-network.\
The module name is tape-r

The following is the output.

root@svl1:~/gubl/fabric-samples/test-network# ./tape-r commitOnly  -c config2.yaml -n 4
empty endorsement policyroot@svl1:~/gubl/fabric-samples/test-network# ./tape-r endorsementOnly -c config2.yaml -n 4
empty endorsement policyroot@svl1:~/gubl/fabric-samples/test-network#

I also try used normal tape, it works well.
root@svl1:~/gubl/fabric-samples/test-network# ./tape -c config2.yaml -n 4
Time     2.08s  Block   3077    Tx      4
tx: 4, duration: 2.082673559s, tps: 1.920608

And for fabric-network, I used fabric 2.4.1 and latest fabric-network
for create channel:
./network.sh createChannel

for deploy chaincode:
 ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-go -ccl go

**Comment by SamYuan1990** [comment]
you may need to apply with endorsement policy as https://github.com/Hyperledger-TWGC/tape/issues/238#issuecomment-1046908882
