### ISSUE TITLE
Avoid importing Fabric pkgs as dependencies

### ISSUE THREAD

**Issue by guoger** [Hyperledger-TWGC/tape#24]
Similar to go-sdk, we should avoid using fabric pkg as dependencies

**Comment by yiwenlong** [comment]
我在自己写一些 fabric 相关的工具的时候也尽量避免引入 fabric pkgs，我的做法是把涉及到 fabric 的代码 copy 到自己的工具项目中。

**Comment by guoger** [comment]
resolved by #158
