### ISSUE TITLE
why  "empty endorsement policy"

### ISSUE THREAD

**Issue by ymkhimself** [Hyperledger-TWGC/tape#256]
When I run my tests on fabcar ,It gave me such an error
![image](https://user-images.githubusercontent.com/73889045/163662734-74e390cc-f3ce-4e5e-a925-dbc9c190945c.png)
The network works. Why is that?

**Comment by SamYuan1990** [comment]
so far we allow user input they own endorsement policy.
hence, a OPA file as endorsement policy describe file is needed.
you are able to ref document below and search with key word `policyFile` for details.
https://github.com/Hyperledger-TWGC/tape/blob/master/docs/configfile.md

**Comment by BIG-KK-the-best** [comment]
> 
谢谢老哥

**Comment by SDU-LYZ** [comment]
> so far we allow user input they own endorsement policy. hence, a OPA file as endorsement policy describe file is needed. you are able to ref document below and search with key word `policyFile` for details. https://github.com/Hyperledger-TWGC/tape/blob/master/docs/configfile.md

thanks bro
