### ISSUE TITLE
why change chaincode name and function name unsuccessfully?

### ISSUE THREAD

**Issue by Z-s-y** [Hyperledger-TWGC/tape#257]
I run the sample "fabcar" and test successfully " peer chaincode query -C mychannel -n fabcar -c '{"Args":["QueryAllCars"]}' " 
then I modify the config.yaml like such:

channel: mychannel
chaincode: fabcar
args:
  - QueryAllCars

why it return the error like this:

time="2022-04-16T22:54:16-07:00" level=error msg="Err processing proposal: %!s(<nil>), status: 500, message: Function CreateAsset not found in contract SmartContract, addr: localhost:9051 \n"

**Comment by SamYuan1990** [comment]
please check your value carefully. :-)
ref CI
https://github.com/Hyperledger-TWGC/tape/runs/5888215910?check_suite_focus=true#step:5:889

https://github.com/Hyperledger-TWGC/tape/runs/5888216566?check_suite_focus=true#step:5:812

value assignment works.

**Comment by SamYuan1990** [comment]
this issue been closed as sample in CI works for now. if you are able to reproduce it via CI by a PR. or the CI fails in coming schedule running, then it makes sense to reopen it.

**Comment by Z-s-y** [comment]
what mean about CI and PR?

**Comment by SamYuan1990** [comment]
> what mean about CI and PR?

continue integration and pull request....

**Comment by Z-s-y** [comment]
I use the instruct "./tape -c config.yaml -n 20"
and the config.yaml is :

# Definition of nodes
# addr address for node
# tls_ca_cert tls cert
peer1: &peer1
  addr: localhost:7051
  tls_ca_cert: ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

peer2: &peer2
  addr: localhost:9051
  tls_ca_cert: ../organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

peer3: &peer3
  addr: localhost:22051
  tls_ca_cert: ../organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp/tlscacerts/tlsca.org3.example.com-cert.pem

peer4: &peer4
  addr: localhost:21051
  tls_ca_cert: ../organizations/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp/tlscacerts/tlsca.org4.example.com-cert.pem

peer5: &peer5
  addr: localhost:23051
  tls_ca_cert: ../organizations/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/msp/tlscacerts/tlsca.org5.example.com-cert.pem

peer6: &peer6
  addr: localhost:24051
  tls_ca_cert: ../organizations/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/msp/tlscacerts/tlsca.org6.example.com-cert.pem

peer7: &peer7
  addr: localhost:25051
  tls_ca_cert: ../organizations/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/msp/tlscacerts/tlsca.org7.example.com-cert.pem

peer3: &peer8
  addr: localhost:26051
  tls_ca_cert: ../organizations/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/msp/tlscacerts/tlsca.org8.example.com-cert.pem

orderer1: &orderer1
  addr: localhost:7050
  tls_ca_cert: ../organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem

policyFile: ./test/andLogic.rego

# Peer Nodes to interact with as endorsement Peers
endorsers:
  - *peer1
  - *peer2
  - *peer3
  - *peer4
  - *peer5
  - *peer6
  - *peer7
  - *peer8

# Peer Nodes to interact with as Commit Peers as listening
committers: 
  - *peer1
  - *peer2
  - *peer3
  - *peer4
  - *peer5
  - *peer6
  - *peer7
  - *peer8
# we might support multi-committer in the future for more complex test scenario.
# i.e. consider tx committed only if it's done on >50% of nodes. 
# Give your commit Threshold as numbers for peers here.
commitThreshold: 8

# orderer Nodes to interact with
orderer: *orderer1

# Invocation configs
channel: mychannel
chaincode: basic
# chain code args below, in a list of str
# we provides 3 kinds of randmon
# uuid
# randomString$length
# randomNumber$min_$max
args:
  - CreateAsset
  - randomString8
  - randomString8
  - randomNumber0_50
  - randomString8
  - randomNumber0_50

# Tx submiter information
mspid: Org1MSP
private_key: ../organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
sign_cert: ../organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
# network traffic control
num_of_conn: 2
client_per_conn: 2

now return the error

time="2022-04-17T05:42:22-07:00" level=error msg="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\""

**Comment by SamYuan1990** [comment]
> received prior goaway: code: ENHA

you'd better debugging your own network by yourself.

**Comment by Z-s-y** [comment]
I can invoke chaincode in cmd correctly.
