### ISSUE TITLE
rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: "too_many_pings" 

### ISSUE THREAD

**Issue by weishengsuB** [Hyperledger-TWGC/tape#258]
└─# ./tape --config=config.yaml --number=1
2022/04/21 20:24:10 debug logging disabled
2022/04/21 20:24:10 debug logging disabled
For FAQ, please check https://github.com/Hyperledger-TWGC/tape/wiki/FAQ
rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: "too_many_pings"    

how to solve this

**Comment by SamYuan1990** [comment]
It's a grpc issue please check your server status.

**Comment by hu-mingwei** [comment]
I have the same problem, how to solve?

**Comment by weishengsuB** [comment]
> I have the same problem, how to solve?

把配置文件好好看看，文件路径啊，函数参数啊，我是这么解决的

**Comment by hu-mingwei** [comment]
我发现自己的错误了，没写org，写了就好了

**Comment by xie-ben** [comment]
> 



> 我发现自己的错误了，没写org，写了就好了

您好，我也遇到同样的错误，请问你的这个org该怎么写

**Comment by Bundchen-1** [comment]
需要好好查看一下配置文件，比如那个.rego文件写对了吗

**Comment by 451735773** [comment]
我加了org还是报错，请问是为什么？这是我的配置文件，用的是Fabric2.4网络。
I added org or reported an error. Why? This is my configuration file, using Fabric 2.4 network.
