### ISSUE TITLE
replace azp by github action

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/tape#259]
currently the only blocking is for release publish, and docker package publish
I found
https://github.com/softprops/action-gh-release
https://docs.github.com/cn/repositories/releasing-projects-on-github/automatically-generated-release-notes
@davidkhala , would you please have a try?

**Comment by davidkhala** [comment]
@SamYuan1990 这个https://github.com/softprops/action-gh-release应该不是来自verified user，而我们TWGC仓库的action设置如下
![image](https://user-images.githubusercontent.com/7227589/168097879-34bb7f16-a2b7-4da6-90ab-6b08e00f4da5.png)

是否需要进一步放宽使用限制？

**Comment by SamYuan1990** [comment]
我们能用
https://docs.github.com/cn/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration
这个么？
github自己的release action好像停止维护了。
如果不行的话我们可能需要咨询一下[ryjones](https://github.com/ryjones) 了

**Comment by davidkhala** [comment]
一个简单的办法是将softprops/action-gh-release@v1加入豁免列表，我正在尝试

**Comment by davidkhala** [comment]
done
