### ISSUE TITLE
update readme with author

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/tape#265]
```
<a href="https://github.com/Hyperledger-TWGC/tape/graphs/contributors">
  <img src="https://contributors-img.web.app/image?repo=Hyperledger-TWGC/tape" />
</a>
```
and it looks like
<a href="https://github.com/Hyperledger-TWGC/tape/graphs/contributors">
  <img src="https://contributors-img.web.app/image?repo=Hyperledger-TWGC/tape" />
</a>

**Comment by MukulKolpe** [comment]
Hey @SamYuan1990, can I work on this issue?
