### ISSUE TITLE
rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: "too_many_pings"

### ISSUE THREAD

**Issue by huniuping** [Hyperledger-TWGC/tape#266]
wen I run the tape ,it report an error : rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: "too_many_pings"
I dont know how to solve this problem,anyone can help me ?
thanks

**Comment by SamYuan1990** [comment]
please do not setting too many connections to peer and check your configuration.

**Comment by SamYuan1990** [comment]
please do not setting too many connections to peer and check your configuration.
