### ISSUE TITLE
使用tape测试Fabric 1.4.4时，当指定的numbers超过200时引起MVCC冲突，求解决方案。

### ISSUE THREAD

**Issue by realcoooool** [Hyperledger-TWGC/tape#271]
另外想问一下，这里的numbers可以理解为并发请求数吗？与配置文件的并发量有什么关系与区别呢？

**Comment by SamYuan1990** [comment]
https://github.com/Hyperledger-TWGC/tape/blob/master/docs/configfile.md

**Comment by realcoooool** [comment]
> https://github.com/Hyperledger-TWGC/tape/blob/master/docs/configfile.md
谢谢回复，我理解的是一次性发送numbers个请求，然后tape通过 num_of_conn * client_per_conn的连接数向fabic发送交易，这样理解对吗？

**Comment by SamYuan1990** [comment]
> > https://github.com/Hyperledger-TWGC/tape/blob/master/docs/configfile.md
> > 谢谢回复，我理解的是一次性发送numbers个请求，然后tape通过 num_of_conn * client_per_conn的连接数向fabic发送交易，这样理解对吗？

建议好好读读文档和设计呢。

**Comment by realcoooool** [comment]
> > > https://github.com/Hyperledger-TWGC/tape/blob/master/docs/configfile.md
> > > 谢谢回复，我理解的是一次性发送numbers个请求，然后tape通过 num_of_conn * client_per_conn的连接数向fabic发送交易，这样理解对吗？
> 
> 建议好好读读文档和设计呢。

好的
