### ISSUE TITLE
tape是否能看到latency数据？

### ISSUE THREAD

**Issue by nk-akun** [Hyperledger-TWGC/tape#276]
在使用tape时，指标数据只能局限在duration、tps上，有没有办法拿到请求的latency指标(最大，最小，平均等)，或者说后期有没有支持计划呢？

**Comment by SamYuan1990** [comment]
已经支持prometheus和open tracing了。

**Comment by SamYuan1990** [comment]
https://github.com/hyperledger-labs/PerformanceSandBox/blob/main/dashboard/fabric/Tape%20Dashboard.json

**Comment by SamYuan1990** [comment]
欢迎提交PR更新tape的dashboard
