### ISSUE TITLE
TPS for Full Process miscalculated

### ISSUE THREAD

**Issue by JingleiPan** [Hyperledger-TWGC/tape#277]
**Describe the bug**
在全流程测试模式中，有两种不同的Observer：BlockCollector 和 CommitObserver。这两种Observer 在观测到指定数目的交易后都会关闭finishCh。然而CommitObserver总是在BlockCollector观测到足够的交易数之前关闭finishCh，这导致计算得到的TPS实际上是从背书开始到orderer出块截至的TPS，并非从背书开始，经由orderer排序最终peer验证落块的全流程TPS。

**To Reproduce**
1. 启动SUT
2. 使用Tape测试（模式全流程）

**Expected behavior**
全流程TPS应该是统计从背书开始到peer落块的TPS，而非背书开始到orderer落块的TPS（只有会peer验证交易有效性）。

**Comment by SamYuan1990** [comment]
checking

**Comment by SamYuan1990** [comment]
Thanks for reporting, try with a pr for fixing it, please verify.

**Comment by JingleiPan** [comment]
似乎finishflag应该加在CommitObserver而不是BlockCollector，因为在全流程模式下CommitObserver关闭finishCh早于BlockCollector。

**Comment by SamYuan1990** [comment]
> 似乎finishflag应该加在CommitObserver而不是BlockCollector，因为在全流程模式下CommitObserver关闭finishCh早于BlockCollector。

毕竟还要考虑其他工作模式。所以现在加了个flag来控制。

**Comment by JingleiPan** [comment]
同意加flag来控制。问题是这个flag加在BlockCollector中，在当前场景无效。
CommitObserver观测的是orderer出块，BlockCollector观测的是peer出块。以fabric的流程来说，总是orderer先完成出块然后才有peer出完所有块(peer接受到来自orderer的区块后还需要检验)。所以CommitObserver会先观测到所有交易已经完成，然后它关闭了finishCh。而BlockCollector此时还尚未接收到所有交易，由于finishCh已经关闭，tape开始计算tps并退出程序。

**Comment by SamYuan1990** [comment]
> 同意加flag来控制。问题是这个flag加在BlockCollector中，在当前场景无效。 CommitObserver观测的是orderer出块，BlockCollector观测的是peer出块。以fabric的流程来说，总是orderer先完成出块然后才有peer出完所有块(peer接受到来自orderer的区块后还需要检验)。所以CommitObserver会先观测到所有交易已经完成，然后它关闭了finishCh。而BlockCollector此时还尚未接收到所有交易，由于finishCh已经关闭，tape开始计算tps并退出程序。

提了个fixing，麻烦确认一下。
