### ISSUE TITLE
Support traffic with constant rate for durability test

### ISSUE THREAD

**Issue by guoger** [Hyperledger-TWGC/tape#45]
We should be able to send tx at constant rate in order to test Fabric durability

**Comment by SamYuan1990** [comment]
Proposer sending rate?

**Comment by SamYuan1990** [comment]
golang.org/x/time/rate 
ref https://www.cnblogs.com/Me1onRind/p/13191506.html
used for create new tx.

**Comment by guoger** [comment]
maybe we could "borrow" some features from jmeter, i.e. step up rate and produce report

**Comment by SamYuan1990** [comment]
> maybe we could "borrow" some ideas from jmeter, i.e. step up rate and produce report

I hope we can have a list of features.
to avoid making stupid not stupid... or we just rename the project then?

**Comment by guoger** [comment]
For durability test, we need to support sending traffic without tx num limit as well
