### ISSUE TITLE
Test peer/orderer **separately**

### ISSUE THREAD

**Issue by guoger** [Hyperledger-TWGC/tape#56]
Often we need to **spot network bottleneck** by testing 3 phases `Endorsement - Order - Commitment` **separately**:
- generate `Proposals` to peer and observe endorsement `ProposalResponse`
- generate `Envelope` to orderers and observe ordered `Block`
- generate `Block` to peer and observed committed `Block` (this is the most tricky one)

This could help us benchmarking fabric components in finer-grained manners.

**Comment by GrapeBaBa** [comment]
Is it finished？
